apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
  labels:
    app: user-service
spec:
  replicas: 3  # Number of container instances to run
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      imagePullSecrets:           # Add this section here
      - name: myregistrykey        # This is the secret name
      containers:
      - name: user-service
        image: Nwdas/user-service:latest  # Replace with your Docker image
        ports:
        - containerPort: 80
