apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: LoadBalancer  # Exposes the service externally
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80  # Must match the containerPort from deployment.yaml

