name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and Push User Service Docker image
        run: |
          docker build -t user-service ./user-service
          docker tag user-service:latest regone/user-service:latest
          docker push regone/user-service:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to AKS
        run: |
          az aks get-credentials --resource-group myResourceGroup --name ci-cd-pipeline
          kubectl apply -f k8s/deployment.yaml

