name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Log in to Azure
        uses: azure/login@v1
        with: 
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push User Service Docker image
        run: |
<<<<<<< HEAD
          docker build -t user-service ./user-service
          docker tag user-service:latest regone/user-service:latest
          docker push regone/user-service:latest
=======
          docker build -t user-service ./user-services  # Ensure this path exists
          docker tag user-service:latest ${{ secrets.DOCKER_USERNAME }}/user-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/user-service:latest
>>>>>>> d311beab81a9baaf55bd74123b5856a8f8b3bb1c

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code          # This is required to access k8s manifests
        uses: actions/checkout@v2

      - name: Log in to Azure
        uses: azure/login@v1
        with: 
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Configure kubectl to use AKS
        run: |
          az aks get-credentials --resource-group myResourceGroup --name ci-cd-pipeline

      - name: Deploy to AKS
        run: |
<<<<<<< HEAD
          az aks get-credentials --resource-group myResourceGroup --name ci-cd-pipeline
=======
>>>>>>> d311beab81a9baaf55bd74123b5856a8f8b3bb1c
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
