name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Log in to Azure
        uses: azure/login@v1
        env:
         CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        with: 
          creds: ${{ env.CREDENTIALS }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          

      - name: Build and Push User Service Docker image
        run: |
          docker build -t user-service ./user-services
          docker tag user-service:latest ${{ secrets.DOCKER_USERNAME }}/user-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/user-service:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to AKS
        run: |
          az aks get-credentials --resource-group myResourceGroup --name ci-cd-pipeline
          kubectl apply -f k8s/deployment.yaml

